dist: trusty
language: node_js
node_js:
  - "11.10.0"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - rm README.md
script:
  - npm run lint
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build/
  on:
    branch: master
