dist: trusty
language: node_js
node_js:
  - "11.10.0"
branches:
  only:
    - master
    - /^feature.*$/
cache:
  directories:
    - node_modules
before_install:
  - rm README.md
script:
  - ./scripts/dependencies.sh
  - ./scripts/test.sh
  - ./scripts/build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: ./web/build/
  on:
    branch: /^release.*$/
