dist: trusty
language: node_js
node_js:
  - "11.10.0"
before_install:
  - rm README.md
script:
  - npm run lint
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
